services:
  - type: web
    name: excel-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python excel_fastmcp_server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: excel-mcp-server
          property: port
